services:
  db:
    image: postgres:16
    container_name: films_db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup_movie:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres_data:
